### ISSUE TITLE
Want improved calendar toggle function

### ISSUE THREAD

**Issue by elthran** [elthran/BookingSystem#10]
In file booking/models/calendars.py, there is a function "def month_toggle()" used in "def business_profile()".  Right now it returns a url_for redirect and then adds on additional data as a string append. But I want this time not happen; I want to pass the data in as parameters, which should already be accepted by the business_profile function. If you can fix this, that would be great. @klondikemarlen

**Comment by elthran** [comment]
Note: I added some comments showing the code that I want, which would be the 4 return statements being re-written.

**Comment by klondikemarlen** [comment]
I'm took a look. I'm honestly not sure what page this is on to test it ... I'll try and figure it out.

**Comment by klondikemarlen** [comment]
I think I've worked out the page :P. I fixed some things ... looks like you have a bunch of HTML errors though.

**Comment by elthran** [comment]
Thanks! It works exactly how I wanted it to now.
