### ISSUE TITLE
Floats

### ISSUE THREAD

**Issue by elthran** [elthran/BookingSystem#20]
I want all prices to be stored to 2 decimal places always (either throw an error r round it if a user types in a 3+ decimal such as $55.765). And I want them to also display that way. So a cost of 5 should show as 5.00 always.

**Comment by klondikemarlen** [comment]
I believe you have 3 issues.
1. Input validation -> restrict to 2 decimal places.
2. Storage -> just store as a float, no restrictions
3. Output formatting -> restrict to correct currency formatting (CAN == 2 decimal places).

**Comment by elthran** [comment]
And I'm sure you can easily solve all 3 of these issues in a few minutes :D

**Comment by klondikemarlen** [comment]
Looks like you set the Storage value to 2 decimal places. I guess I'll leave that for now.

**Comment by klondikemarlen** [comment]
Working in https://github.com/elthran/BookingSystem/tree/issue_20

**Comment by klondikemarlen** [comment]
Fixed in https://github.com/elthran/BookingSystem/pull/22
