### ISSUE TITLE
Clients search page.

### ISSUE THREAD

**Issue by elthran** [elthran/BookingSystem#21]
business/clients.py 
business/clients.html

These pages show you a list of every client in your business. By typing in the search bar and pressing search, it should ONLY show you clients matching that search. This will either by a name, email, or phone number. Can you try to make this happen?

In the future we will add an auto-complete search with JS but it should run the same search code anyway, so no need to wait for that.

**Comment by klondikemarlen** [comment]
I started ... but dam that is a lot of work.

**Comment by klondikemarlen** [comment]
Fixed in https://github.com/elthran/BookingSystem/pull/25
